apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector.morven.me
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      #namespace: sidecar-injector
      namespace: default
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01EUXhNekEwTVRRME5sb1hEVE13TURReE1qQTBNVFEwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUEyCnYwT2VzeWRiUWpKTzl0VEtZQUNORGpLUmJXd1ZTVHhaLzdCZ2VoaGRzL3RRN2pyY1Axbi84dTVwZG9jaWZITVMKYkZFalNGSlFpSDJmbmhBR1djbm92Q2g5U3VycTMwU29rU1JSdjUvQWNOLzIxYUtteDdMK3BhTWNWOGpNcWpsUQpPcGVCbDlzaHJCYUp5RC8zcmdxeUZhNCt2cGhRNWtTaWNzL0pQblQvdWNuR2hxTkgxcWlETFZuZ0hFMVo1S1U1Cm5UZTQ4UTZQOFErN3pPVmVteG5URFN4QVNPdGxpT0Rxa2lZQkNoSGZGNG9zTERjL3BsbGQvZTRKV0o1eGU2V0QKQUdUSkJqbFpNbDhBazlvV3o3NmNJcGQ0b0g2bnkwV2V6ckNHMmwrZTF2aGV5TW1uSHp2VnM4ZW5iTkFGUUhYVwpoZGdjUTlzbmdRbmV2Skh6NnVrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDOGtUR1pYc01udy9YN3NWaWNZM3JGeDFWUVpmc3YxN1pmMHl3U01TQTR0c1UzZEEvUwptOFZnMEswZ0tjK25ub0Y3NzRGUnl3YnJFTTJob29FWG5ySFNmNmVNa3pOVTVPTlFPKzg3UWovczh4cWt0Y0JQCksyNjYzZzJIZXlQUllQT0t4ZDZOeHlyZ1hJNWk0TVBpYWRMTEg4SklHekdVZGFpRjdHcm83Y0FlZ3dpcVhZeisKYVhCejhpUzhmLzJkZGNFN0U3QXZuRDEyU2ZoT2RycnlBTlhlN2VCTVk1ZlROdlNNTFhXdHRaWTZpd0kwbXpybgpuYkNNVHEwVjVNeEt0bS9YQ2hJcjI4ZVJDRkRHT2V6Zk02Sm5ET0ZhZ2VCRW5PNWZwTlplekdSZHhkSkN0QlFSCkYzR2xGdmxNOWNGUTk0Vnl5bndPVzVPSjJRYnBDWGZkSlZWdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
